version: '2'
services:
  shifu:
    environment:
      - "BUNDLE_PATH=/shifu/.gems"
    working_dir: /shifu
    build: .
    volumes:
      - "./:/shifu"
    command: "bin/rails s --bind '0.0.0.0' --port 3000"
    ports:
      - "3000:3000"
    depends_on: 
      - database_shifu
      - webpack-dev-server
    links:
      - database_shifu:database_shifu

  webpack-dev-server:
    environment:
      - "BUNDLE_PATH=/shifu/.gems"
    working_dir: /shifu
    build: .
    volumes:
      - "./:/shifu"
    command: "bundle exec webpack --watch"

  database_shifu:
    image: postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

